# Site settings
title: "Test Jekyll"
description: "whatever"
baseurl: ""
url: "http://yin.deming.im"
assetUrl: "https://raw.githubusercontent.com/yindmeing/yindeming.github.io/master/images/post/"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "Page 1"
    url: /page1
  - title: "My Github"
    url: http://github.com/yindeming
